---
- name: Install nginx package
  apt:
    update_cache: true
    pkg:
      - nginx
    state: present

- include_tasks: install_dependencies.yml
  when: dependencies | length > 0

- name: "Create www directory for your virtualhost"
  ansible.builtin.file:
    path: /var/www/{{ domain }}
    state: directory
    mode: '0775'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Delete default nginx site configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Set up sites available 
  ansible.builtin.template:
    src: "{{ context }}/templates/{{ item }}.j2"
    dest: /etc/nginx/sites-available/{{ item }}
  with_items: "{{ servers }}"
  notify: restart nginx

- name:  Set up sites enabled
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    state: link
  with_items: "{{ servers }}"
  notify: restart nginx

- name: Set up main NGINX configuration
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Change index.html
  ansible.builtin.template:
    src: "{{ context }}/templates/{{ html_file }}"
    dest: "/var/www/{{domain}}/index.html"
    mode: '0775'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: test NGINX configuration
  ansible.builtin.command: nginx -t
  changed_when: false
  notify: restart nginx
