---
- name: Install nginx package
  apt:
    update_cache: true
    pkg:
      - nginx
    state: present

- name: "Create www directory for your virtualhost"
  ansible.builtin.file:
    path: /var/www/{{ domain }}
    state: directory
    mode: '0775'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Delete default nginx site configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: Rescue block
  block:
    - name: Include NGINX configuration files
      ansible.builtin.template:
        src: templates/{{ item }}.j2
        dest: /etc/nginx/conf.d/{{ item }}
      with_items: "{{ includes }}"

- name: Set up main NGINX configuration
  ansible.builtin.template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: change index.html
  ansible.builtin.copy:
    src: "{{ html_file_path }}"
    dest: "/var/www/{{domain}}/index.html"
    mode: '0775'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: test NGINX configuration
  ansible.builtin.command: nginx -t
  changed_when: false
  notify: restart nginx
